#!/bin/bash
# Linted by https://www.shellcheck.net/

# This script aims to harvest .json files generated by logrotate,
# compress and upload them to S3.

market_type=$1

# Infinite while loop
while :
do
  sleep 60
  # Find .json files and compress them
  find "$DATA_DIR/$market_type" -name "*.json" -type f | shuf | xargs -r -n 1 -P 4 pigz -f
  rclone move "$DATA_DIR/$market_type" "$AWS_S3_DIR/$market_type" --include '*.json.gz' --no-traverse --transfers=8
done
