name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

# Stop the previous CI tasks (which is deprecated)
# to conserve the runner resource.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Cargo build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

  test:
    name: Cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: taiki-e/install-action@nextest
      - uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Run cargo nextest
        run: |
          # Run all tests except:
          # * bitmex, because bitmex has very low rate limit
          # * FTX, the FTX website is not operational
          # * zbg, due to the "invalid peer certificate: UnknownIssuer" error
          cargo nextest run -E 'all() - binary(~bitmex) - binary(~ftx) - binary(~zbg)'

          # Run the '*bitmex*' tests in -j1.
          cargo nextest run -E 'binary(~bitmex)' -j1 || true

  doc-test:
    name: Cargo doctest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --doc

  fmt:
    name: Cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  check:
    name: Cargo check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check

  clippy:
    name: Cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
